<?xml version="1.0"?>
<robot name="cafe_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--                Dimensions              -->
    <xacro:property name="chassis_length" value="0.45"/>
    <xacro:property name="chassis_width" value="0.4"/>
    <xacro:property name="chassis_height" value="0.2"/>
    <xacro:property name="wheel_thk" value="0.05"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="lidar_radius" value="0.06"/>
    <xacro:property name="lidar_height" value="0.05"/>
    <xacro:property name="support_height" value="0.65"/>
    <xacro:property name="support_radius" value="0.01"/>
    <xacro:property name="support_pos_z" value="0.425"/>
    
    <!--                Macro for Defining Inertia                  -->
    <xacro:macro name="sphere_inertia" params="mass radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(2/5) * mass * (radius*radius)}" ixy="0.0" ixz="0.0"
                    iyy="${(2/5) * mass * (radius*radius)}" iyz="0.0"
                    izz="${(2/5) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>  

    <xacro:macro name="box_inertia" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                    izz="${(1/12) * mass * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>


    <xacro:macro name="cylinder_inertia" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>



    <!--                Base Link               -->
    <link name="base_link"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint"/>



    <!--                Chassis Joint               -->
    <joint name="chassis_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>

    <link name="chassis_link">
        <inertial>
            <xacro:box_inertia mass="2.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:box_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="dark">
                <color rgba="1.0 1.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
    </link>
    


    <!--            Left Wheel Joint                -->
    <joint name="wheel_L_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_L_link"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0 0.225 -0.04" rpy="1.57 0 0"/>
    </joint>
    
    <link name="wheel_L_link">
        <inertial>
            <xacro:cylinder_inertia mass="1.0" length="${wheel_thk}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy=" 0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thk}"/> 
            </geometry>
            <material name="grey">
                <color rgba="0.1 0.7 0.7 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thk}"/> 
            </geometry>
        </collision>
    </link>



    <!--                Right Wheel Joint               -->
    <joint name="wheel_R_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_R_link"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0 -0.225 -0.04" rpy="1.57 0 0"/>
    </joint>
    
    <link name="wheel_R_link">
        <inertial>
            <xacro:cylinder_inertia mass="1.0" length="${wheel_thk}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thk}"/> 
            </geometry>
            <material name="grey">
                <color rgba="0.1 0.7 0.7 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thk}"/> 
            </geometry>
        </collision>
    </link>



    <!--                Caster wheel joints & links              -->
    <joint name="caster_wheelF_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheelF"/>
        <origin xyz="0.15 0 -0.1" rpy="0.0 0 0"/>
    </joint>
    
    <link name="caster_wheelF">
        <inertial>
            <xacro:sphere_inertia mass="0.15" radius="0.03">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:sphere_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy=" 0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="0.03"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="0.03"/>
            </geometry>
        </collision>
    </link>

    <joint name="caster_wheelB_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheelB"/>
        <origin xyz="-0.15 0 -0.1" rpy="0.0 0 0"/>
    </joint>
    
    <link name="caster_wheelB">
        <inertial>
            <xacro:sphere_inertia mass="0.15" radius="0.03">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:sphere_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy=" 0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="0.03"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="0.03"/>
            </geometry>
        </collision>
    </link>



    <!--                Laser joint & link              -->
    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_frame"/>
        <origin xyz="0 0 0.125" rpy="0.0 0 0"/>
    </joint>
    
    <link name="lidar_frame">
        <inertial>
            <xacro:cylinder_inertia mass="0.200" length="${lidar_height}" radius="${lidar_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy=" 0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/> 
            </geometry>
            <material name="orange">
                <color rgba="1.0 0.3 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/> 
            </geometry>
        </collision>
    </link>



    <!--            Support Frames              -->
    <joint name="support1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="support1"/>
        <origin xyz="0.18 0.15 ${support_pos_z}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="support1">
        <inertial>
            <xacro:cylinder_inertia mass="0.3" length="${support_height}" radius="${support_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
                <texture />
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.02" length="0.2"/>
            </geometry>
        </collision>
    </link>

    <joint name="support2_joint" type="fixed">
        <parent link="base_link"/>
        <child link="support2"/>
        <origin xyz="-0.18 -0.15 ${support_pos_z}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="support2">
        <inertial>
            <xacro:cylinder_inertia mass="0.3" length="${support_height}" radius="${support_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
                <texture />
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.02" length="0.2"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="support3_joint" type="fixed">
        <parent link="base_link"/>
        <child link="support3"/>
        <origin xyz="-0.18 0.15 ${support_pos_z}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="support3">
        <inertial>
            <xacro:cylinder_inertia mass="0.3" length="${support_height}" radius="${support_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
                <texture />
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.02" length="0.2"/>
            </geometry>
        </collision>
    </link>

    <joint name="support4_joint" type="fixed">
        <parent link="base_link"/>
        <child link="support4"/>
        <origin xyz="0.18 -0.15 ${support_pos_z}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="support4">
        <inertial>
            <xacro:cylinder_inertia mass="0.3" length="${support_height}" radius="${support_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
                <texture />
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.02" length="0.2"/>
            </geometry>
        </collision>
    </link>


    <!--                Level Frames              -->
    <joint name="level1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="level1"/>
        <origin xyz="0 0 0.25" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="level1">
        <inertial>
            <xacro:cylinder_inertia mass="0.3" length="${wheel_thk}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size = "${chassis_length} ${chassis_width} 0.02"/>
            </geometry>
            <material name="dark">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size = "0 0 0"/>
            </geometry>
        </collision>
    </link>

    <joint name="level2_joint" type="fixed">
        <parent link="base_link"/>
        <child link="level2"/>
        <origin xyz="0 0 0.5" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="level2">
        <inertial>
            <xacro:cylinder_inertia mass="0.3" length="${wheel_thk}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size = "${chassis_length} ${chassis_width} 0.02"/>
            </geometry>
            <material name="dark">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size = "0 0 0"/>
            </geometry>
        </collision>
    </link>


    <joint name="level3_joint" type="fixed">
        <parent link="base_link"/>
        <child link="level3"/>
        <origin xyz="0 0 0.75" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="level3">
        <inertial>
            <xacro:cylinder_inertia mass="0.3" length="${wheel_thk}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertia>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size = "${chassis_length} ${chassis_width} 0.02"/>
            </geometry>
           <material name="dark">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size = "0 0 0"/>
            </geometry>
        </collision>
    </link>

    <!--                Gazebo Plugins              -->
    <gazebo reference="lidar_frame">

        <sensor name="laser" type="gpu_lidar">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </lidar>
            <topic>scan</topic>
            <gz_frame_id>laser_frame</gz_frame_id>
        </sensor>
    </gazebo>

    <gazebo>
        <plugin name="gz::sim::systems::DiffDrive" filename="gz-sim-diff-drive-system">

            <!-- Wheel Info -->
            <left_joint>wheel_L_joint</left_joint>
            <right_joint>wheel_R_joint</right_joint>
            <wheel_separation>${chassis_width + wheel_thk}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>


            <!-- Limits -->
            <max_linear_acceleration>0.33</max_linear_acceleration>

            <!-- Input -->
            <topic>cmd_vel</topic>

            
            <!-- Output -->
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>
            <odom_topic>odom</odom_topic>
            <odom_publisher_frequency>30</odom_publisher_frequency>
            
            <tf_topic>/tf</tf_topic>

        </plugin>


        <plugin filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic>
            <joint_name>wheel_L_joint</joint_name>
            <joint_name>wheel_R_joint</joint_name>
        </plugin>
    </gazebo>

</robot>